version: '3'
services:
  download-service:
    image: download-service
    build:
      context: ./download-service
    ports:
      - "8081:8080"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  upload-service:
    image: upload-service
    build:
      context: ./upload-service
    ports:
      - "8082:8080"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  metadata-service:
    image: metadata-service
    build:
      context: ./metadata-service
    ports:
      - "8083:8080"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod

networks:
  app-network:
    driver: bridge
